language: python

python:
  - "2.7"
  - "3.0"
  - "3.2"

before_script:
  - pip install -r requirements.txt
  - pip install nose

script:
  - nosetests --with coverage

after_success :
  -  coveralls
